// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyewWr90xxjAihsyyLaN1rk-GSHH8SSPs',
    appId: '1:955870033341:web:fbd125cf3d4bf4d08c4ed4',
    messagingSenderId: '955870033341',
    projectId: 'mudarribe-fitness',
    authDomain: 'mudarribe-fitness.firebaseapp.com',
    storageBucket: 'mudarribe-fitness.appspot.com',
    measurementId: 'G-15J78P7340',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbTtOQ1czNPWEljEtx9gn62vJbXrCxzsQ',
    appId: '1:955870033341:android:b967aeeadf4f5f328c4ed4',
    messagingSenderId: '955870033341',
    projectId: 'mudarribe-fitness',
    storageBucket: 'mudarribe-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBr4yqaRrWHq_VXDlr0RcHLxCZRSiiCo',
    appId: '1:955870033341:ios:a3f349982b228a4f8c4ed4',
    messagingSenderId: '955870033341',
    projectId: 'mudarribe-fitness',
    storageBucket: 'mudarribe-fitness.appspot.com',
    iosBundleId: 'com.mudarribe.trainer.mudarribeTrainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBr4yqaRrWHq_VXDlr0RcHLxCZRSiiCo',
    appId: '1:955870033341:ios:3ac20e61ac7a78bb8c4ed4',
    messagingSenderId: '955870033341',
    projectId: 'mudarribe-fitness',
    storageBucket: 'mudarribe-fitness.appspot.com',
    iosBundleId: 'com.mudarribe.trainer.mudarribeTrainer.RunnerTests',
  );
}
